name: umol
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ambertools=23.3=py312h1577c9a_6
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.1.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h98912ed_4
  - arpack=3.8.0=nompi_h0baa96a_101
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.5=h0f2a231_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py312h30efb56_1
  - bson=0.5.9=py_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.23.0=hd590300_0
  - c-blosc2=2.11.3=hb4ffafa_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.2=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.11.17=py312h06a4308_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - chex=0.1.85=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h8572e83_0
  - cuda-version=11.8=h70ddcb2_2
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.0=py312h30efb56_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dm-tree=0.1.7=py312h6a678d5_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - fftw=3.3.10=nompi_hc118613_108
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.46.0=py312h98912ed_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - greenlet=3.0.2=py312h30efb56_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=py312h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h7900ff3_3
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.11.2=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.20.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py312h7900ff3_0
  - jupyter_events=0.9.0=pyhd8ed1ab_0
  - jupyter_server=2.12.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.0=pyhd8ed1ab_0
  - jupyterlab=4.0.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.25.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.2=h659d440_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py312hfb10629_6
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.3=h783c2da_0
  - libgomp=13.2.0=h807b86a_3
  - libgrpc=1.58.2=he06187c_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnetcdf=4.9.2=nompi_h80fb2b6_112
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.24.3=hf27288f_1
  - libre2-11=2023.06.02=h7a70373_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.6=h232c23b_0
  - libxslt=1.1.37=h0054252_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - lxml=4.9.3=py312he528aba_3
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.3=py312h98912ed_1
  - matplotlib-base=3.8.2=py312he5832f3_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_0
  - mdtraj=1.9.9=py312hadb1fa1_1
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - ml_dtypes=0.3.1=py312hfb8ada1_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.12.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nccl=2.19.4.1=h6103f9b_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - netcdf-fortran=4.6.1=nompi_hacb5139_103
  - networkx=3.2.1=pyhd8ed1ab_0
  - notebook=7.0.6=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.2=py312hc5e2394_0
  - numpy-base=1.26.2=py312h0da6c21_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openff-amber-ff-ports=0.0.4=pyhca7485f_0
  - openff-forcefields=2023.11.0=pyhca7485f_0
  - openff-interchange=0.3.18=pyhd8ed1ab_0
  - openff-interchange-base=0.3.18=pyhd8ed1ab_0
  - openff-models=0.1.1=pyhca7485f_0
  - openff-toolkit=0.14.5=pyhd8ed1ab_1
  - openff-toolkit-base=0.14.5=pyhd8ed1ab_1
  - openff-units=0.2.1=pyh1a96a4e_0
  - openff-utilities=0.1.12=pyhd8ed1ab_0
  - openjpeg=2.5.0=h488ebb8_3
  - openmm=8.1.0=py312hc343695_1
  - openmmforcefields=0.11.2=pyhd8ed1ab_1
  - openssl=3.2.0=hd590300_1
  - opt-einsum=3.3.0=hd8ed1ab_2
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - packmol=20.010=h86c2bf4_0
  - pandas=2.1.4=py312hfb8ada1_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panedr=0.7.2=pyhd8ed1ab_0
  - parmed=4.2.2=py312h30efb56_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pbr=6.0.0=pyhd8ed1ab_0
  - pcre2=10.42=hcad00b1_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - perl=5.32.1=4_hd590300_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.1.0=py312hf3581a9_0
  - pint=0.21=pyhd8ed1ab_0
  - pip=23.3.1=py312h06a4308_0
  - pixman=0.42.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py312h98912ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pycairo=1.25.1=py312he48a392_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=2.5.2=pyhd8ed1ab_0
  - pydantic-core=2.14.5=py312h4b3b743_0
  - pyedr=0.7.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.9.2=py312h5531bb7_1
  - python=3.12.0=hab00c5b_0_cpython
  - python-constraint=1.4.0=py_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - pyzmq=25.1.2=py312h886d080_0
  - rdkit=2023.09.3=py312hd93e07f_1
  - re2=2023.06.02=h2873b5e_0
  - readline=8.2=h5eee18b_0
  - referencing=0.32.0=pyhd8ed1ab_0
  - reportlab=4.0.7=py312h98912ed_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.13.2=py312h4b3b743_0
  - scipy=1.11.4=py312hc5e2394_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.0.0=py312h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smirnoff99frosst=1.1.0=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.23=py312h98912ed_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.0=pyh0d859eb_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tinydb=4.8.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=py312h06a4308_0
  - tornado=6.3.3=py312h98912ed_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3eb1b0_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.41.2=py312h06a4308_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.11.0=py312h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.0.0
      - amberutils==21.0
      - biopython==1.81
      - click==8.1.7
      - contextlib2==21.6.0
      - dm-haiku==0.0.11
      - edgembar==0.2
      - etils==1.6.0
      - flatbuffers==23.5.26
      - flax==0.7.5
      - fsspec==2023.12.1
      - gast==0.5.4
      - google-auth==2.25.2
      - google-auth-oauthlib==1.1.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - immutabledict==2.0.0
      - jax==0.4.19
      - jaxlib==0.4.21+cuda12.cudnn89
      - jmp==0.0.4
      - keras-nightly==3.0.1.dev2023121103
      - libclang==16.0.6
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - mmpbsa-py==16.0
      - msgpack==1.0.7
      - namex==0.0.7
      - nvidia-cublas-cu12==12.3.4.1
      - nvidia-cuda-cupti-cu12==12.3.101
      - nvidia-cuda-nvcc-cu12==12.3.103
      - nvidia-cuda-nvrtc-cu12==12.3.103
      - nvidia-cuda-runtime-cu12==12.3.101
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.0.12.1
      - nvidia-cusolver-cu12==11.5.4.101
      - nvidia-cusparse-cu12==12.2.0.103
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - oauthlib==3.2.2
      - optax==0.1.4
      - orbax-checkpoint==0.4.7
      - packmol-memgen==2023.2.24
      - pdb4amber==22.0
      - protobuf==4.25.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - sander==22.0
      - svgwrite==1.4.3
      - tabulate==0.9.0
      - tb-nightly==2.16.0a20231211
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.51
      - termcolor==2.4.0
      - tf-estimator-nightly==2.14.0.dev2023080308
      - tf-keras-nightly==2.16.0.dev2023121110
      - tf-nightly==2.16.0.dev20231211
      - tree==0.2.4
      - werkzeug==3.0.1
      - wrapt==1.14.1
prefix: /proj/berzelius-2023-267/users/x_patbr/software/miniconda3/envs/jax_bio
